name: Upload

on:
  workflow_dispatch:
    inputs:
      package_run_id:
        description: ''
        required: false
        default: ''
  workflow_call:
    inputs:
      package_run_id:
        description: 'Package workflow run id'
        required: false
        type: string

permissions:
  actions: read
  contents: read

env:
  BUNDLE_DIRECTORY: bundle

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Download bundle (same run)
        if: ${{ (inputs.package_run_id == '' || inputs.package_run_id == null) && (github.event.inputs.package_run_id == '' || github.event.inputs.package_run_id == null) }}
        uses: actions/download-artifact@v4
        with:
          name: msixbundle
          path: ${{ env.BUNDLE_DIRECTORY }}

      - name: Download bundle (using run-id)
        if: ${{ (inputs.package_run_id != '' && inputs.package_run_id != null) || (github.event.inputs.package_run_id != '' && github.event.inputs.package_run_id != null) }}
        uses: actions/download-artifact@v4
        with:
          name: msixbundle
          path: ${{ env.BUNDLE_DIRECTORY }}
          run-id: ${{ inputs.package_run_id != '' && inputs.package_run_id || github.event.inputs.package_run_id }}

      - name: Publish to Store
        uses: isaacrlevin/windows-store-action@1.0
        with:
          tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
          client-id: ${{ secrets.ENTRA_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.ENTRA_APPLICATION_SECRET }}
          app-id: ${{ secrets.STORE_APP_ID }}
          package-path: "${{ env.BUNDLE_DIRECTORY }}"